# Part 1: introduction

In [1]:
import pandas as pd

In [140]:
df = pd.read_csv("./developer_survey_2019/survey_results_public.csv")

In [3]:
df.shape

(88883, 85)

In [4]:
#get the first five rows of the complete data
#df.head()

In [5]:
#get the general information of the data
df.describe()

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,88883.000000,5.594500e+04,5.582300e+04,64503.000000,49790.000000,79210.000000
mean,44442.000000,5.519014e+11,1.271107e+05,42.127197,5.084308,30.336699
std,25658.456325,7.331926e+13,2.841523e+05,37.287610,5.513931,9.178390
min,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,1.000000
25%,22221.500000,2.000000e+04,2.577750e+04,40.000000,2.000000,24.000000
50%,44442.000000,6.200000e+04,5.728700e+04,40.000000,4.000000,29.000000
75%,66662.500000,1.200000e+05,1.000000e+05,44.750000,6.000000,35.000000
max,88883.000000,1.000000e+16,2.000000e+06,4850.000000,99.000000,99.000000

In [6]:
pd.set_option("display.max_columns",85)
pd.set_option("display.max_rows",85)

In [7]:
schema_df = pd.read_csv("./developer_survey_2019/survey_results_schema.csv", index_col='Column')

In [8]:
#schema_df

#Part 2: DataFrames

In [9]:
people ={
    "name":["sahil","ajit","shreya"],
    "last":["gupta","yadav","soni"],
    "email":["sg@email.com","ay@email.com","ss@email.com"]
}

In [10]:
people['email']

['sg@email.com', 'ay@email.com', 'ss@email.com']

In [11]:
type(people['email'])

list

Dataframe can be understood by reading a python dictionay, to convert to dataframe we can use pd.DataFrame() method

In [12]:
people_df= pd.DataFrame(people)
people_df

     name   last         email
0   sahil  gupta  sg@email.com
1    ajit  yadav  ay@email.com
2  shreya   soni  ss@email.com

In [13]:
people_df['email'] # people.email will give same output

0    sg@email.com
1    ay@email.com
2    ss@email.com
Name: email, dtype: object

In [14]:
type(people_df['email'])

pandas.core.series.Series

In [15]:
people_df[['name','email']]

     name         email
0   sahil  sg@email.com
1    ajit  ay@email.com
2  shreya  ss@email.com

In [16]:
type(people_df[['name','email']])

pandas.core.frame.DataFrame

In [17]:
people_df.columns

Index(['name', 'last', 'email'], dtype='object')

In [18]:
#to get rows
people_df.iloc[[0,2]]

     name   last         email
0   sahil  gupta  sg@email.com
2  shreya   soni  ss@email.com

In [19]:
#get rows for some specific columns
people_df.iloc[[0,2],[2]]

          email
0  sg@email.com
2  ss@email.com

In [20]:
people_df.loc[[0,1],['last','name']] #can get dataframes by changing the columns order

    last   name
0  gupta  sahil
1  yadav   ajit

Working on stackoverflow data

In [21]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [22]:
#how many of answered yes and no
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [23]:
#get specific row and columns 
df.loc[[0,3,5,56],'Hobbyist']

0     Yes
3      No
5     Yes
56    Yes
Name: Hobbyist, dtype: object

In [24]:
df.loc[0:10,'Hobbyist'] #list slicing on rows

0     Yes
1      No
2     Yes
3      No
4     Yes
5     Yes
6      No
7     Yes
8     Yes
9     Yes
10    Yes
Name: Hobbyist, dtype: object

In [25]:
df.loc[0:10,'Hobbyist':'Employment'] #list slicing on rows as well as on columns ; boundaries are inclusive

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time
3,No,Never,The quality of OSS and closed source software ...,Employed full-time
4,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time
5,Yes,Never,The quality of OSS and closed source software ...,Employed full-time
6,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em..."
7,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work"
8,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time
9,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time
10,Yes,Once a month or more often,The quality of OSS and closed source software ...,NaN

# part 3: Indexing

In [26]:
#using people_df for simplicity

people_df['email']

0    sg@email.com
1    ay@email.com
2    ss@email.com
Name: email, dtype: object

In [27]:
people_df.set_index('email',inplace=True)

In [28]:
people_df

                name   last
email
sg@email.com   sahil  gupta
ay@email.com    ajit  yadav
ss@email.com  shreya   soni

In [29]:
people_df.loc['sg@email.com',['last','name']]

last    gupta
name    sahil
Name: sg@email.com, dtype: object

In [30]:
#to reset index
people_df.reset_index(inplace=True)

In [31]:
#working on stackoverflow data

df.set_index('Respondent',inplace=True)

In [32]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [33]:
#df.loc[1] #get the 1st respondent data

In [34]:
schema_df.loc['MgrIdiot','QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [35]:
schema_df.sort_index(ascending=False,inplace=True)
schema_df

                                                             QuestionText
Column
YearsCodePro            How many years have you coded professionally (...
YearsCode               Including any education, how many years have y...
WorkWeekHrs              On average, how many hours per week do you work?
WorkRemote                                How often do you work remotely?
WorkPlan                          How structured or planned is your work?
WorkLoc                                   Where would you prefer to work?
WorkChallenge           Of these options, what are your greatest chall...
WelcomeChange           Compared to last year, how welcome do you feel...
WebFrameWorkedWith      Which of the following web frameworks have you...
WebFrameDesireNextYear  Which of the following web frameworks have you...
UnitTests               Does your company regularly employ unit tests ...
UndergradMajor          What was your main or most important field of ...
Trans                                     Do you identify as transgender?
SurveyLength            How do you feel about the length of the survey...
SurveyEase              How easy or difficult was this survey to compl...
Student                 Are you currently enrolled in a formal, degree...
SocialMedia                   What social media site do you use the most?
Sexuality               Which of the following do you currently identi...
ScreenName                                           What do you call it?
SOVisitTo               I visit Stack Overflow to... (check all that a...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisit1st              To the best of your memory, when did you first...
SOTimeSaved             Think back to the last time you solved a codin...
SOPartFreq              How frequently would you say you participate i...
SONewContent            Would you like to see any of the following on ...
SOJobs                  Have you ever used or visited Stack Overflow J...
SOHowMuchTime           About how much time did you save? If you're no...
SOFindAnswer            On average, how many times a week do you find ...
SOComm                  Do you consider yourself a member of the Stack...
SOAccount                           Do you have a Stack Overflow account?
ResumeUpdate            Think back to the last time you updated your r...
Respondent              Randomized respondent ID number (not in order ...
PurchaseWhat            What level of influence do you, personally, ha...
PurchaseHow             How does your company make decisions about pur...
PlatformWorkedWith      Which of the following platforms have you done...
PlatformDesireNextYear  Which of the following platforms have you done...
OrgSize                 Approximately how many people are employed by ...
OpenSourcer                   How often do you contribute to open source?
OpenSource              How do you feel about the quality of open sour...
OpSys                   What is the primary operating system in which ...
OffOn                         Have you tried turning it off and on again?
MiscTechWorkedWith      Which of the following other frameworks, libra...
MiscTechDesireNextYear  Which of the following other frameworks, libra...
MgrWant                 Do you want to become a manager yourself in th...
MgrMoney                Do you believe that you need to be a manager t...
MgrIdiot                How confident are you that your manager knows ...
MainBranch              Which of the following options best describes ...
LastInt                 In your most recent successful job interview (...
LastHireDate            When was the last time that you took a job wit...
LanguageWorkedWith      Which of the following programming, scripting,...
LanguageDesireNextYear  Which of the following programming, scripting,...
JobSeek                 Which of the following best describes your cur...
JobSat                  How satisfied are you with your current job? (...
JobFactors              Imagine that you are deciding between two job ...
ImpSyn                  For the specific work you do, and the years of...
ITperson                 Are you the "IT support person" for your family?
Hobbyist                                          Do you code as a hobby?
Gender                  Which of the following do you currently identi...
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
Extraversion              Do you prefer online chat or IRL conversations?
Ethnicity               Which of the following do you identify as? Ple...
EntTeams                Have you ever used Stack Overflow for Enterpri...
Employment              Which of the following best describes your cur...
EduOther                Which of the following types of non-degree edu...
EdLevel                 Which of the following best describes the high...
DevType                 Which of the following describe you? Please se...
DevEnviron              Which development environment(s) do you use re...
Dependents              Do you have any dependents (e.g., children, el...
DatabaseWorkedWith      Which of the following database environments h...
DatabaseDesireNextYear  Which of the following database environments h...
CurrencySymbol          Which currency do you use day-to-day? If your ...
CurrencyDesc            Which currency do you use day-to-day? If your ...
Country                         In which country do you currently reside?
ConvertedComp           Salary converted to annual USD salaries using ...
Containers              How do you use containers (Docker, Open Contai...
CompTotal               What is your current total compensation (salar...
CompFreq                 Is that compensation weekly, monthly, or yearly?
CodeRevHrs              On average, how many hours per week do you spe...
CodeRev                          Do you review code as part of your work?
CareerSat               Overall, how satisfied are you with your caree...
BlockchainOrg           How is your organization thinking about or imp...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BetterLife              Do you think people born today will have a bet...
Age1stCode              At what age did you write your first line of c...
Age                     What is your age (in years)? If you prefer not...

# Part 4: Filtering

##### we can get the vlaues from the dataframe for a specific conditinons,
###### here below we get the name of the person who's lastname is 'yadav'

In [36]:
filt = (people_df['last'] == 'yadav')

In [37]:
people_df[filt][['name','last']] #gives dataframe

   name   last
1  ajit  yadav

In [38]:
people_df.loc[filt,'email'] #gives series

1    ay@email.com
Name: email, dtype: object

In [39]:
filt = (people_df['name'] == 'sahil') | (people_df['last'] == 'soni')

In [40]:
people_df[filt]

          email    name   last
0  sg@email.com   sahil  gupta
2  ss@email.com  shreya   soni

In [41]:
people_df[~filt] #not filter

          email  name   last
1  ay@email.com  ajit  yadav

In [42]:
#working on stackoverflow data
high_salary = (df['ConvertedComp']>700000)
df[high_salary][['Country','LanguageWorkedWith','ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
32,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,1100000.0
58,United States,C#;Java;SQL,2000000.0
102,United States,C#;HTML/CSS;JavaScript;SQL;TypeScript,2000000.0
128,United Kingdom,Bash/Shell/PowerShell;Go;Ruby,1000000.0
155,Germany,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Type...,962424.0
...,...,...,...
88815,United States,HTML/CSS;Java;JavaScript;Kotlin;Python;SQL,2000000.0
88818,United States,C#;HTML/CSS;JavaScript;SQL;TypeScript,2000000.0
88868,Germany,HTML/CSS;JavaScript;PHP;TypeScript,797436.0
88874,United States,C++;Python;Scala;SQL,2000000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0

In [43]:
countaries = ['India']
#this filter only return values of the countries listed above. moreover we are adding one more condition that 
# get the values of those developers who have some experience in python language
filt = df['Country'].isin(countaries) & (df['LanguageWorkedWith'].str.contains('Python',na=False))

In [44]:
#filter itself returns the series of the statisfied rows form the table 
filt

Respondent
1        False
2        False
3        False
4        False
5        False
         ...
88377    False
88601    False
88802    False
88816    False
88863    False
Length: 88883, dtype: bool

In [45]:
df[filt]['Student'].value_counts() # counts values gives the frequency of the categorical columns

No                1788
Yes, full-time    1144
Yes, part-time      94
Name: Student, dtype: int64

# Part 5: updating rows and columns

In [46]:
people_df.columns

Index(['email', 'name', 'last'], dtype='object')

In [47]:
people_df.columns = ['first_name','last_name','email']

In [48]:
people_df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [49]:
people_df.columns = [x.lower() for x in people_df.columns]

In [50]:
people_df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [51]:
people_df.rename(columns={'first_name':'email','last_name':'first','email':'last'},inplace=True)

In [52]:
people_df

          email   first   last
0  sg@email.com   sahil  gupta
1  ay@email.com    ajit  yadav
2  ss@email.com  shreya   soni

In [53]:
people_df.loc[2]= ['pb@gmail','pranay','bagrechaa']

In [54]:
people_df

          email   first       last
0  sg@email.com   sahil      gupta
1  ay@email.com    ajit      yadav
2      pb@gmail  pranay  bagrechaa

In [55]:
people_df.loc[2,['last','email']] = ['soni','ss@gmail.com']

In [56]:
#people_df.loc[2,['first']] = ['shreya'] is same as
people_df.at[2,['first']] = ['shreya']

 Be careful while modifying data, always reassign values via .loc\[\] or .at[]
 When filter is applied to the data without using 'loc' or 'at' it returns the copy of the dataframe statisfied to filter
 eg: poeple_df\[(some kind of filter)\] will gives copy, modification of the data will fail.
 the link in warning explains the diffrence.

In [57]:
filt = people_df['first'] == 'sahil'
people_df[filt]['last'] = 'Gupta'

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

To modify data successfully use .loc or .at with filter.

In [58]:
people_df.loc[filt,['last']] = 'Gupta'
people_df

          email   first   last
0  sg@email.com   sahil  Gupta
1  ay@email.com    ajit  yadav
2  ss@gmail.com  shreya   soni

### four methods for accessing and updating
### 1) apply
### 2) applymap
### 3) map
### 4) replace

---
1) apply

In [59]:
people_df['email'].apply(len)

0    12
1    12
2    12
Name: email, dtype: int64

In [60]:
def update_email(email):
    return email.upper()

people_df['email'].apply(update_email) 
#this does'nt change the original values to  do it just with the update columns

0    SG@EMAIL.COM
1    AY@EMAIL.COM
2    SS@GMAIL.COM
Name: email, dtype: object

In [61]:
people_df['email'].apply(lambda x: x.lower())

0    sg@email.com
1    ay@email.com
2    ss@gmail.com
Name: email, dtype: object

To get the length of the dataframe we can easily use apply function of len with dataframe
axis='rows' for length of rows

In [62]:
people_df.apply(len,axis='rows')

email    3
first    3
last     3
dtype: int64

In [63]:
people_df.apply(pd.Series.min)

email    ay@email.com
first            ajit
last            Gupta
dtype: object

2) applymap, only used for Dataframe for every individual values

In [64]:
people_df.applymap(len)

   email  first  last
0     12      5     5
1     12      4     5
2     12      6     4

 3) map function takes key:value pairs which replace each occurence of the key with the given value and makes every "not mentioned" keys to NaN
 
4) whereas replace method does same as map but keep values as it was originally which are not mentioned.

#### working  on stackoverflow data

In [65]:
df.rename(columns= {'ConvertedComp': 'SalaryUSD'},inplace=True)

In [66]:
#change hobbyist values to boolean
df['Hobbyist'] = df['Hobbyist'].map({'Yes':True,'No':False})
df['Hobbyist']

Respondent
1         True
2        False
3         True
4        False
5         True
         ...
88377     True
88601    False
88802    False
88816    False
88863     True
Name: Hobbyist, Length: 88883, dtype: bool

#### adding and removing columns

In [67]:
people_df['full_name'] = people_df['first']+' '+people_df['last']

In [68]:
people_df

          email   first   last    full_name
0  sg@email.com   sahil  Gupta  sahil Gupta
1  ay@email.com    ajit  yadav   ajit yadav
2  ss@gmail.com  shreya   soni  shreya soni

In [69]:
#remobe first and last name column 
people_df.drop(columns=['first','last'],inplace=True)

In [70]:
people_df

          email    full_name
0  sg@email.com  sahil Gupta
1  ay@email.com   ajit yadav
2  ss@gmail.com  shreya soni

In [71]:
# I realized i need those deleted columns
people_df['full_name'].str.split(' ',expand=True)

        0      1
0   sahil  Gupta
1    ajit  yadav
2  shreya   soni

In [72]:
people_df[['first','last']] = people_df['full_name'].str.split(' ',expand=True)

In [73]:
people_df

          email    full_name   first   last
0  sg@email.com  sahil Gupta   sahil  Gupta
1  ay@email.com   ajit yadav    ajit  yadav
2  ss@gmail.com  shreya soni  shreya   soni

In [74]:
#adding rows 
people_df.append({'first':'Juned'},ignore_index=True)

          email    full_name   first   last
0  sg@email.com  sahil Gupta   sahil  Gupta
1  ay@email.com   ajit yadav    ajit  yadav
2  ss@gmail.com  shreya soni  shreya   soni
3           NaN          NaN   Juned    NaN

In [75]:
#append new dataframe
new_people = {
    'first':['mark','lucy'],
    'last': ['watney','blake']
}
people_df2 = pd.DataFrame(new_people)

In [76]:
people_df = people_df.append(people_df2,ignore_index=True)

In [77]:
people_df

          email    full_name   first    last
0  sg@email.com  sahil Gupta   sahil   Gupta
1  ay@email.com   ajit yadav    ajit   yadav
2  ss@gmail.com  shreya soni  shreya    soni
3           NaN          NaN    mark  watney
4           NaN          NaN    lucy   blake

In [78]:
#removing rows
people_df.drop([3,4],inplace=True)

# Part 6: Sorting data

In [79]:
people_df.sort_values(by="first" , ascending=False)

          email    full_name   first   last
2  ss@gmail.com  shreya soni  shreya   soni
0  sg@email.com  sahil Gupta   sahil  Gupta
1  ay@email.com   ajit yadav    ajit  yadav

In [80]:
people_df =people_df.append({'email':'sk@gmail.com','full_name':'sahil watney','first':'sahil','last':'watney'},ignore_index=True)

In [81]:
#if last_name is same then it will sort with first name
people_df.sort_values(by=['last','first'], ascending=[False,True])

          email     full_name   first    last
1  ay@email.com    ajit yadav    ajit   yadav
3  sk@gmail.com  sahil watney   sahil  watney
2  ss@gmail.com   shreya soni  shreya    soni
0  sg@email.com   sahil Gupta   sahil   Gupta

In [82]:
people_df['email'].sort_values()

1    ay@email.com
0    sg@email.com
3    sk@gmail.com
2    ss@gmail.com
Name: email, dtype: object

#### working on stackoverlfow data

In [83]:
df.sort_values(by='Country',inplace=True)

In [84]:
df[['Country','SalaryUSD']].head(50)

                Country  SalaryUSD
Respondent
39258       Afghanistan    19152.0
63129       Afghanistan  1000000.0
85715       Afghanistan        NaN
50767       Afghanistan        NaN
2782        Afghanistan        NaN
63019       Afghanistan        NaN
6417        Afghanistan        NaN
40000       Afghanistan        NaN
88731       Afghanistan        NaN
48436       Afghanistan     4464.0
10746       Afghanistan     3996.0
62525       Afghanistan        NaN
49702       Afghanistan        NaN
33178       Afghanistan        NaN
60946       Afghanistan        NaN
86362       Afghanistan        NaN
88582       Afghanistan        NaN
28638       Afghanistan        0.0
722         Afghanistan        0.0
26340       Afghanistan        NaN
86932       Afghanistan        NaN
85825       Afghanistan        NaN
7085        Afghanistan    14364.0
7353        Afghanistan        NaN
87091       Afghanistan        NaN
58760       Afghanistan        NaN
74386       Afghanistan        NaN
29045       Afghanistan        NaN
51859       Afghanistan        NaN
45854       Afghanistan        NaN
47110       Afghanistan        NaN
44403       Afghanistan        NaN
22450       Afghanistan     7980.0
8149        Afghanistan     1596.0
80926       Afghanistan        NaN
59560       Afghanistan        NaN
60569       Afghanistan        NaN
37802       Afghanistan        NaN
29736       Afghanistan     1116.0
43106       Afghanistan        NaN
12310       Afghanistan        NaN
58450       Afghanistan    17556.0
62168       Afghanistan        NaN
50499       Afghanistan   153216.0
78817           Albania     4968.0
57419           Albania        NaN
49757           Albania        NaN
41608           Albania        NaN
33385           Albania        NaN
6716            Albania    60000.0

In [85]:
# sort on country ascending and salary in descending order
df.sort_values(by=['Country','SalaryUSD'],ascending=[True,False],inplace=True)

In [86]:
df[['Country','SalaryUSD']].head(50)

                Country  SalaryUSD
Respondent
63129       Afghanistan  1000000.0
50499       Afghanistan   153216.0
39258       Afghanistan    19152.0
58450       Afghanistan    17556.0
7085        Afghanistan    14364.0
22450       Afghanistan     7980.0
48436       Afghanistan     4464.0
10746       Afghanistan     3996.0
8149        Afghanistan     1596.0
29736       Afghanistan     1116.0
28638       Afghanistan        0.0
722         Afghanistan        0.0
85715       Afghanistan        NaN
50767       Afghanistan        NaN
2782        Afghanistan        NaN
63019       Afghanistan        NaN
6417        Afghanistan        NaN
40000       Afghanistan        NaN
88731       Afghanistan        NaN
62525       Afghanistan        NaN
49702       Afghanistan        NaN
33178       Afghanistan        NaN
60946       Afghanistan        NaN
86362       Afghanistan        NaN
88582       Afghanistan        NaN
26340       Afghanistan        NaN
86932       Afghanistan        NaN
85825       Afghanistan        NaN
7353        Afghanistan        NaN
87091       Afghanistan        NaN
58760       Afghanistan        NaN
74386       Afghanistan        NaN
29045       Afghanistan        NaN
51859       Afghanistan        NaN
45854       Afghanistan        NaN
47110       Afghanistan        NaN
44403       Afghanistan        NaN
80926       Afghanistan        NaN
59560       Afghanistan        NaN
60569       Afghanistan        NaN
37802       Afghanistan        NaN
43106       Afghanistan        NaN
12310       Afghanistan        NaN
62168       Afghanistan        NaN
38308           Albania   187668.0
3787            Albania   114550.0
9270            Albania    74474.0
6716            Albania    60000.0
10303           Albania    57300.0
66280           Albania    41244.0

In [87]:
df['SalaryUSD'].nlargest(10) #is same as df.nlargest(10,'SalaryUSD')

Respondent
25983    2000000.0
87896    2000000.0
22013    2000000.0
28243    2000000.0
72732    2000000.0
78151    2000000.0
80200    2000000.0
52132    2000000.0
75561    2000000.0
32250    2000000.0
Name: SalaryUSD, dtype: float64

In [88]:
 df.nsmallest(10,'SalaryUSD') #but this will result with complete dataframe instead of Series

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
28638,I am a developer by profession,True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,NaN,NaN,NaN,36,13,16,Very dissatisfied,Very dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NaN,NaN,NaN,NaN,NaN,AFN,Afghan afghani,3.0,Monthly,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Java;Objective-C;O...,Bash/Shell/PowerShell;C;C++;Java;Objective-C;O...,MySQL;SQLite,MySQL;SQLite,Android;iOS;Linux;MacOS,Android;iOS;Linux,jQuery,NaN,TensorFlow;Unity 3D,Hadoop;TensorFlow;Unity 3D,Emacs,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,No,NaN,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,6-10 times per week,The other resource was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","No, not at all",A lot less welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN
722,I am a developer by profession,False,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,NaN,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,Less than 1 year,Younger than 5 years,Less than 1 year,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,NaN,No,NaN,I heard about a job opportunity (from a recrui...,AFN,Afghan afghani,1.0,Yearly,0.0,1.0,NaN,NaN,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",1.0,"No, and I'm glad we don't",NaN,I have little or no influence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,SIGH,What?,NaN,Neither,NaN,2008,Multiple times per day,NaN,More than 10 times per week,The other resource was much faster,60+ minutes,Not sure / can't remember,NaN,Yes,Yes,Not sure,Not applicable - I did not use Stack Overflow ...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Too long,Difficult
13825,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,NaN,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,13,83,Less than 1 year,Very dissatisfied,Very satisfied,NaN,NaN,NaN,I am actively looking for a job,NA - I am an independent contractor or self em...,Complete a take-home project;Solve a brain-tea...,Yes,Financial performance or funding status of the...,"Something else changed (education, award, medi...",AFN,Afghan afghani,1.0,Yearly,0.0,168.0,NaN,Being tasked with non-development work;Non-wor...,About half the time,Home,Far above average,No,NaN,"Yes, it's part of our process",NaN,I have a great deal of influence,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,NaN,NaN,I do not use containers,NaN,An irresponsible use of resources,No,Yes,Yes,NaN,Neither,NaN,2015,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",A lot less welcome now than last year,NaN,56.0,NaN,NaN,NaN,NaN,Yes,Too short,Easy
40913,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Armenia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",2-9 employees,"Developer, desktop or enterprise applications;...",7,15,4,Slightly satisfied,Slightly satisfied,Very confident,Not sure,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",AMD,Armenian dram,0.0,Monthly,0.0,40.0,There's no schedule or spec; I work on what se...,"Meetings;Non-work commitments (parenting, scho...","Less than half the time, but at least one day ...",Office,A little above average,"Yes, because I see value in code review",3.0,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;C;C++;Java;JavaScript;Py...,C;C++;Java;Python;SQL;TypeScript,Elasticsearch;MariaDB;MongoDB;MySQL;Redis,MariaDB;MongoDB;MySQL,Arduino;AWS;Docker;Linux;MacOS;Raspberry Pi;Sl...,Arduino;Linux;MacOS;Raspberry Pi,ASP.NET;Django;Flask,Django;Flask,.NET;Node.js;TensorFlow;Torch/PyTorch,Node.js,IntelliJ;IPython / Jupyter;Sublime Text;Vim,Linux-based,Production,Not at all,A passing fad,No,SIGH,Yes,Facebook,In real life (in person),Username,2013,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers,22.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
30630,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,2-9 employees,"Database administrator;Developer, back-end;Dev...",35,7,30,Neither satisfied nor dissatisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,Interview with people in peer roles;Interview ...,No,Industry that I'd be working in;Office environ...,I heard about a job opportunity (from a recrui...,AUD,Australian dollar,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what se...,Distracting work environment;Non-work commitme...,It's complicated,"Other place, such as a coworking space or cafe",A little above average,"Yes, because I see value in code review",10.0,"No, but I think we should",NaN,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Ruby,Elixir;Ruby;TypeScript,PostgreSQL,PostgreSQL,AWS;iOS,Android;AWS;iOS,Ruby on Rails;Vue.js,Ruby on Rails;Vue.js,Chef;React Native,React Native,Sublime Text;TextMate;Vim;Xcode,MacOS,I do not use containers,Not at all,An irresponsible use of resources,Yes,"Fortunately, someone else has that title",No,Reddit,Online,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",A lot less welcome now than last year,NaN,43.0,NaN,No,NaN,NaN,No,Appropriate in length,Easy
69049,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,2-9 employees,"Developer, full-stack;Engineering manager",17,12,14,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",AUD,Australian dollar,0.0,Yearly,0.0,25.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Time spent com...,All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",1.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C#;Go;HTML/CSS;JavaScr...,Dart;Elixir;JavaScript;Kotlin;Python;R;Ruby;Rust,PostgreSQL;SQLite,Cassandra;PostgreSQL;Redis,Android;Arduino;Google Cloud Platform;iOS;Linu...,Google Cloud Platform;Heroku;Kubernetes;Linux;...,Ruby on Rails,Ruby on Rails;Vue.js,.NET;React Native,Ansible;Flutter;Hadoop;Pandas;React Native,IntelliJ;Visual Studio;Visual Studio Code;Xcode,MacOS,Production,NaN,A passing fad,No,Also Yes,Yes,Reddit,In real life (in person),Username,2008,A few times per week,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Not sure / can't remember,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",Just as welcome now as I felt last year,NaN,34.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
19340,"I am not primarily a developer, but I write co...",True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",NaN,Austria,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Fine arts or performing arts (ex. graphic desi...,Taken an online course in programming or softw...,NaN,NaN,10,20,5,Neither satisfied nor dissatisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",3-4 years ago,Interview with people in peer roles;Interview ...,No,Office environment or company culture;Opportun...,I was preparing for a job search,CHF,Swiss franc,0.0,Monthly,0.0,35.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,Average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have a great deal of influence,Assembly;C;Elixir;HTML/CSS;Java;JavaScript;Pyt...,Clojure,PostgreSQL;SQLite,NaN,Arduino;Raspberry Pi,Arduino;Raspberry Pi,Other(s):,Other(s):,NaN,NaN,IntelliJ;Sublime Text,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful for immutable record keeping outside of...,No,Also Yes,Yes,NaN,In real life (in person),Username,2010,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,NaN,32.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
16214,"I am not primarily a developer, but I write co...",True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",NaN,20 to 99 employees,"Engineer, data;Engineering manager;Product man...",20,16,20,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Interview with people in peer roles,No,Financial performance or funding status of the...,I was preparing for a job search,EUR,European Euro,0.0,Yearly,0.0,10.0,There's no schedule or spec; I work on what se...,Lack of support from management;Meetings;Time ...,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,No,NaN,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,Java;PHP;Other(s):,Java;PHP;Other(s):,MariaDB;MySQL,MariaDB;MySQL,Android;Linux;Raspberry Pi;Windows;WordPress,Android;Linux;Raspberry Pi;Windows;WordPress,jQuery;Spring,jQuery;Spring,NaN,NaN,Android Studio;Eclipse;IntelliJ;NetBeans,Linux-based,I do not use containers,Not at all,NaN,No,Yes,What?,WhatsApp,Neither,NaN,2008,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,99.0,NaN,No,NaN,NaN,NaN,Too long,Easy
29355,I am a developer by profession,True,Never,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",Bosnia and Herzegovina,"Yes, part-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","Just me - I am a freelancer, sole proprietor, ...",NaN,10,10,6,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,Less than a year ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Specific depar...,"Something else changed (education, award, medi...",BAM,Bosnia and Herzegovina convertible mark,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Inadequ...,It's complicated,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",20.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Python;Ruby;Other(s):,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;Oth...,NaN,NaN,Linux;MacOS;Microsoft Azure;Raspberry Pi;Windows,Android;Arduino;AWS;iOS;Linux;MacOS;Raspberry ...,NaN,NaN,Pandas;TensorFlow;Torch/PyTorch;Unity 3D;Unrea...,.NET;Torch/PyTorch;Unity 3D,Android Studio;Emacs;PyCharm;Visual Studio;Vis...,Linux-based,I do not use containers,NaN,A passing fad,Yes,Also Yes,Yes,YouTube,In real life (in person),Username,2013,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,NaN,No,NaN,NaN,NaN,Too long,Easy
1685,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Brazil,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...","Designer;Developer, full-stack;Developer, game...",8,16,3,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,Specific department or team I'd be working on;...,I was preparing for a job search,BRL,Brazilian real,0.0,Monthly,0.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Toxic wo...,All or almost all the time (I'm full-time remote),Home,Average,"Yes, because I see value in code review",6.0,NaN,NaN,NaN,Elixir;HTML/CSS;JavaScript;PHP;Python,C#;Kotlin;Python,Cassandra;MariaDB;MongoDB;PostgreSQL,Cassandra;MariaDB;MongoDB;PostgreSQL,Docker;Kubernetes;MacOS,Android;Linux;Windows,Laravel,Django;Flask;Laravel;Vue.js,Node.js,.NET;Node.js;Unity 3D;Other(s):,Android Studio;PHPStorm;PyCharm;Visual Studio ...,Windows,Development,NaN,Useful across many domains and could change ma...,No,Yes,Yes,WhatsApp,In real life (in person),NaN,2010,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Neither easy nor difficult

# Part 7: Grouping and Aggregating

In [89]:
 df.rename(columns={
    'SalaryUSD': 'ConvertedComp'
 },inplace=True)

In [90]:
df['ConvertedComp'].median()

57287.0

In [91]:
df.median()

Hobbyist             1.0
CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [92]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [93]:
df['ConvertedComp'].count()

55823

In [94]:
df['Hobbyist'].value_counts()

True     71257
False    17626
Name: Hobbyist, dtype: int64

In [95]:
df['SocialMedia']

Respondent
63129    I don't use social media
50499                    WhatsApp
39258                    Facebook
58450                    Facebook
7085                    Instagram
                   ...
88062                         NaN
88076                         NaN
88601                         NaN
88802                         NaN
88816                         NaN
Name: SocialMedia, Length: 88883, dtype: object

In [96]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [97]:
df['SocialMedia'].value_counts(normalize=True)

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

In [98]:
# split apply combine

In [99]:
df['Country'].value_counts(normalize=True)

United States            0.236042
India                    0.102095
Germany                  0.066095
United Kingdom           0.064642
Canada                   0.038253
                           ...
Chad                     0.000011
Sao Tome and Principe    0.000011
Brunei Darussalam        0.000011
Dominica                 0.000011
Tonga                    0.000011
Name: Country, Length: 179, dtype: float64

In [100]:
country_grp = df.groupby(['Country'])

In [101]:
country_grp.get_group('India')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
22013,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,2-9 employees,Academic researcher;Data scientist or machine ...,3,26,3,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",USD,United States dollar,1.500000e+06,Weekly,2000000.0,50.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Meetings;...,All or almost all the time (I'm full-time remote),Home,A little below average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have a great deal of influence,Assembly;Bash/Shell/PowerShell;C;C++;Java;Java...,Python;Swift,Cassandra;Microsoft SQL Server;Oracle,Cassandra,Android;Arduino;Google Cloud Platform;IBM Clou...,IBM Cloud or Watson;Windows,jQuery,NaN,TensorFlow,TensorFlow,Visual Studio;Visual Studio Code,Windows,Development,Implementing our own cryptocurrency,Useful across many domains and could change ma...,Yes,Yes,No,YouTube,Online,Screen Name,NaN,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,Yes,"Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28243,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Developer, back-end;Developer, full-stack;Deve...",25,9,14,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles;Interview ...,Yes,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,USD,United States dollar,2.000000e+06,Yearly,2000000.0,20.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Not eno...,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",NaN,NaN,NaN,NaN,C++;C#;Java;JavaScript;Objective-C;Python,C;C++;C#,PostgreSQL;SQLite,SQLite,Android;AWS;iOS;MacOS;Windows,Android;Linux,NaN,NaN,Node.js;Pandas;Unity 3D,Unity 3D;Unreal Engine,Android Studio;Coda;PyCharm;Visual Studio;Visu...,MacOS,I do not use containers,NaN,An irresponsible use of resources,No,Yes,No,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,Multiple times per day,Yes,"No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72732,"I am not primarily a developer, but I write co...",False,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,NaN,NaN,4,20,5,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am actively looking for a job,More than 4 years ago,Write any code,No,Remote work options;Opportunities for professi...,I was preparing for a job search,USD,United States dollar,8.000000e+04,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Meetings;Time ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Not sure,I have little or no influence,Java;Python;SQL,NaN,MongoDB;Microsoft SQL Server;MySQL;Oracle;Post...,MySQL,Android;Windows,AWS;Docker,NaN,Angular/Angular.js;React.js,NaN,NaN,Eclipse;Notepad++;PyCharm,Windows,Testing,NaN,NaN,Yes,Yes,No,WhatsApp,Neither,NaN,2017,A few times per month or weekly,Get a sense of belonging to the developer comm...,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are",Not sure,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
80923,I am a developer by profession,True,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,India,NaN,NaN,NaN,Taken an online course in programming or softw...,NaN,Scientist,10,14,11,Neither satisfied nor dissatisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",More than 4 years ago,"Write any code;Write code by hand (e.g., on a ...",NaN,Industry that I'd be working in;Opportunities ...,I heard about a job opportunity (from a recrui...,SEK,Swedish krona,2.000000e+11,Yearly,1000000.0,NaN,NaN,Meetings,Less than once per month / Never,NaN,Far above average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Not sure,NaN,C#;Dart;HTML/CSS;Java;JavaScript;Kotlin;Object...,Python;WebAssembly,MongoDB;MySQL;Oracle;SQLite,Cassandra;Couchbase,Android;Arduino;Google Cloud Platform;iOS;MacO...,AWS;Docker;Linux,Drupal;Express;React.js,Django;Spring;Vue.js,Cordova;Flutter;Node.js;React Native;Xamarin,TensorFlow;Torch/PyTorch;Unity 3D,Android Studio;Eclipse;IntelliJ;Notepad++;Visu...,MacOS,"Development;Outside of work, for personal proj...",NaN,NaN,Yes,Also Yes,Yes,I don't use social media,Neither,NaN,2008,I have never visited Stack Overflow (before to...,Contribute to a library of information,Less than once per week,They were about the same,NaN,NaN,NaN,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult
78265,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time",NaN,NaN,Taken an online course in programming or softw...,"10,000 or more employees",Data or business analyst,More than 50 years,Older than 85,More than 50 years,Very satisfied,Slightly satisfied,Very confident,NaN,Yes,"I’m not actively looking, but I am open to new...",NA - I am an independent contractor or self em...,Write any code;Complete a take-home project,Yes,Specific department or team I'd be working on,"My job status changed (promotion, new job, etc.)",INR,Indian rupee,1.000000e+08,Weekly,1000000.0,24.0,NaN,Lack of support from management,It's complicated,Home,A little above average,No,NaN,"Yes, it's part of our process",NaN,I have some influence,Assembly;Bash/Shell/PowerShell;C;C++;C#;Clojur...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Clojur...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Android;Arduino,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Angular/Angular.js;ASP.NET;Django;Drupal;Expre...,Angular/Angular.js;ASP.NET;Django;Drupal;Expre...,Ansible;Apache Spark;Chef;Cordova;CryEngine;Fl...,Ansible;Apache Spark;Chef;Cordova;CryEngine;Fl...,Android Studio;Atom;Coda;Eclipse;Emacs;Intelli...,Windows,I do not use containers,Accepting Bitcoin or other coins and tokens as...,Useful across many domains and could change ma...,Yes,SIGH,No,YouTube,Online,Screen Name,2018,Daily or almost daily,Get a sense of belonging to the developer comm...,Less than once per week,The other resource was much faster,60+ minutes,Yes,Daily or almost daily,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",A lot less welcome now than last year,Tech articles written by other developers,18.0,"Woman;Man;Non-binary, genderqueer, or gender n...",NaN,NaN,NaN,Yes,Too short,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79312,I am a student who is learning to code,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,NaN,Data or business analyst;Data scientist or mac...,5,18,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,NaN,NaN,"Languages, frameworks, and other technologies ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;Go;HTML/CSS;Java;JavaScript;Objective-C;...,Go;HTML/CSS;Java;JavaScript;Kotlin;PHP;Python;...,MariaDB;MongoDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;MySQL;Oracle;SQLite,Android;AWS;Heroku;Linux;Windows,Android;AWS;Heroku;Linux,Django;Express;jQuery,Django;Express;jQuery,Apache Spark;Hadoop;Node.js;Pandas,Apache Spark;Hadoop;Node.js;Pandas,Android Studio;IntelliJ;IPython / Jupyter;NetB...,Linux-based,Development,NaN,Useful across many domains and could change ma...,Yes,Yes,No,LinkedIn,Online,Login,2014,Multiple times per day,Find answers to specific questions;Learn how t...,Less than once per week,They were about the same,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,NaN,23.0,Man,NaN,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
79628,I am a developer by profession,False,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,India,No,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,"Developer, mobile",3,17,3,Very satisfied,Very satisfied,Somewhat confident,No,Not sure,I am not interested in new job opportunities,3-4 years ago,Solve a brain-teaser style puzzle,No,Industry that I'd be working in;How widely use...,I was preparing for a job search,INR,Indian rupee,NaN,NaN,NaN,NaN,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Non-work ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",4.0,"No, but I think we should",Developers and management have nearly equal in...,I have little or no influence,JavaScript,HTML/CSS;JavaScript,NaN,NaN,Android;iOS,Android;iOS,React.js,React.js,React Native,React Native,Atom,MacOS,I do not use containers,NaN,NaN,Yes,Also Yes,NaN,Twitter,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,Man,NaN,NaN,South Asian,NaN,Too long,Easy
40151,NaN,False,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",NaN,India,No,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,NaN,Less than 1 year,15,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;TypeScript,Erlang;HTML/CSS;Java;Kotlin,Cassandra,Firebase;Microsoft SQL Server;MySQL;Oracle,Android;Linux;MacOS;Microsoft Azure;Slack;Windows,iOS;MacOS,ASP.NET;Flask;React.js;Ruby on Rails,React.js,Hadoop;Node.js;Pandas;TensorFlow;Unity 3D;Unre...,Torch/PyTorch,Android Studio;Atom;NetBeans;Sublime Text;Visu...,MacOS,Development;Testing;Production;Outside of work...,NaN,A passing fad,No,Yes,Yes,Instagram,In real life (in person),Username,2017,Less than once per month or monthly,Learn how to do things I didn’t necessarily lo...,Less than once per week,The other resource was much faster,11-30 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",A lot more welcome now than last year,Tech meetups or events in your area,NaN,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
76400,"I am not primarily a developer, but I write co...",False,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,Data or business analyst;Database administrato...,24,19,22,Very dissatisfied,Very dissatisfied,NaN,NaN,NaN,I am actively looking for a job,3-4 years ago,Interview with people in senior / management r...,No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,INR,Indian rupee,NaN,NaN,NaN,NaN,There is a schedule and/or spec (made by me or...,Distracting work environment;Inadequate access...,It's complicated,Office,Far above average,"Yes, because I see value in code review",15.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;Java;SQL,Bash/Shell/PowerShell;C++;HTML/CSS;Java;SQL,MySQL;Oracle,Oracle;PostgreSQL;SQLite,Android;Docker;Kubernetes;Linux;Windows,Android;Arduino;Kubernetes;Linux;Windows,NaN,NaN,Cordova;Node.js;React Native,Cordova;Hadoop;Node.js;React Native;Xamarin,Android Studio;Eclipse;Notepad++,Linux-based,Development;Testing;Production,Not at all,NaN,Yes,Yes,No,WhatsApp,Online,UserID,2009,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,60+ minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
30452,I am a student who is learning to code,False,Never,"OSS is, on average, of HIGHER quality than pro...",NaN,India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,3,15,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,Industry that I'd be working in;Office environ...,I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;SQL,Bash/Shell/PowerShell;C#;PHP;Python,Microsoft SQL Server;MySQL;Oracle,DynamoDB;Firebase;MongoDB,Android,Android;AWS;WordPress,Angular/Angular.js;jQuery,Angular/Angular.js;Django;jQuery;Laravel;Vue.js,NaN,Flutter;Node.js;React Native;TensorFlow,Android Studio;NetBeans;Notepad++;PyCharm;Visu...,Windows,Development,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,No,YouTube,Neither,Username,2016,A few times per month or weekly,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are",Not sure,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult

In [102]:
# This is what groupby does but for each unique value of the country column
filt = (df['Country']=='India')
df.loc[filt]['SocialMedia'].value_counts()

WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [103]:
# with loc() method now we can look for any country social media preference without changing and applying filter again and again
country_grp['SocialMedia'].value_counts(normalize=True).loc['China']

SocialMedia
WeChat 微信                   0.670549
YouTube                     0.088186
Weibo 新浪微博                  0.069884
I don't use social media    0.044925
Twitter                     0.044925
Reddit                      0.019967
LinkedIn                    0.018303
Facebook                    0.013311
Instagram                   0.011647
Youku Tudou 优酷              0.011647
WhatsApp                    0.004992
VK ВКонта́кте               0.001664
Name: SocialMedia, dtype: float64

In [104]:
country_grp['ConvertedComp'].median().loc['India']

10080.0

In [105]:
country_grp['ConvertedComp'].agg(['mean','median']).loc['India']

mean      28057.664916
median    10080.000000
Name: India, dtype: float64

In [106]:
# looking for python developers by applying filter
filt = (df['Country'] == 'India') 
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [107]:
# this is not way you should use filtering on a grouped dataframe; it gives error because it applies method to the whole Series
# instead of applying to each value of the series
country_grp['LanguageWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [108]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [110]:
# how many % of people uses python in a country
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
total_respondents = df['Country'].value_counts()
total_respondents

United States            20949
India                     9061
Germany                   5866
United Kingdom            5737
Canada                    3395
                         ...
Chad                         1
Sao Tome and Principe        1
Brunei Darussalam            1
Dominica                     1
Tonga                        1
Name: Country, Length: 179, dtype: int64

In [111]:
python_d =pd.concat([total_respondents,country_uses_python],axis='columns')

In [112]:
python_d.head(50)

                    Country  LanguageWorkedWith
United States         20949               10083
India                  9061                3105
Germany                5866                2451
United Kingdom         5737                2384
Canada                 3395                1558
France                 2391                1054
Brazil                 1948                 767
Poland                 1922                 751
Australia              1903                 790
Netherlands            1852                 767
Russian Federation     1694                 708
Spain                  1604                 641
Italy                  1576                 625
Sweden                 1274                 496
Switzerland             978                 460
Israel                  952                 457
Turkey                  949                 371
Pakistan                923                 251
Ukraine                 868                 246
Austria                 839                 338
Czech Republic          764                 285
Romania                 760                 253
Iran                    738                 268
Belgium                 727                 296
China                   664                 297
Bulgaria                659                 181
Mexico                  642                 245
South Africa            627                 202
Denmark                 617                 246
Bangladesh              605                 204
Norway                  574                 232
Greece                  556                 226
Argentina               553                 191
Finland                 546                 266
Portugal                525                 182
New Zealand             524                 236
Nigeria                 522                 152
Hungary                 513                 191
Indonesia               507                 148
Ireland                 501                 209
Serbia                  402                 117
Japan                   391                 182
Philippines             381                 117
Sri Lanka               372                 137
Egypt                   323                 111
Colombia                313                 108
Singapore               303                 139
Malaysia                299                  95
Slovenia                298                 119
Croatia                 260                  87

In [113]:
python_d.rename(columns={'Country':'NumRespondents','LanguageWorkedWith':'NumKnowsPython'},inplace=True)

In [114]:
python_d['PctKnowsPython'] = (python_d['NumKnowsPython']/python_d['NumRespondents']) * 100

In [115]:
python_d.sort_values(by='PctKnowsPython',ascending=False,inplace=True)
python_d.loc['India']

NumRespondents    9061.000000
NumKnowsPython    3105.000000
PctKnowsPython      34.267741
Name: India, dtype: float64

# Part 8: Casting dtype and handling missing values

In [127]:
people_df = people_df.append({'first':'juned','last':'khan','full_name':'juned khan'},ignore_index=True)
people_df

          email     full_name   first    last
0  sg@email.com   sahil Gupta   sahil   Gupta
1  ay@email.com    ajit yadav    ajit   yadav
2  ss@gmail.com   shreya soni  shreya    soni
3  sk@gmail.com  sahil watney   sahil  watney
4           NaN           NaN   juned    khan
5           NaN    juned khan   juned    khan

In [120]:
#remove missing data
people_df.dropna()

          email     full_name   first    last
0  sg@email.com   sahil Gupta   sahil   Gupta
1  ay@email.com    ajit yadav    ajit   yadav
2  ss@gmail.com   shreya soni  shreya    soni
3  sk@gmail.com  sahil watney   sahil  watney

In [125]:
#dropna with default argument
people_df.dropna(axis='index', how='all') #only delete rows when all the data is missing
people_df.dropna(axis='columns', how='all') #only delete columns when all the data is missing
people_df.dropna(axis='columns', how='any') #only delete columns when any one of them the data is missing

    first    last
0   sahil   Gupta
1    ajit   yadav
2  shreya    soni
3   sahil  watney
4   juned    khan

In [129]:
people_df.dropna(axis='index', how='all',subset=['email']) #only delete specific rows when any one of them the data is missing

          email     full_name   first    last
0  sg@email.com   sahil Gupta   sahil   Gupta
1  ay@email.com    ajit yadav    ajit   yadav
2  ss@gmail.com   shreya soni  shreya    soni
3  sk@gmail.com  sahil watney   sahil  watney

In [130]:
people_df.isna()

   email  full_name  first   last
0  False      False  False  False
1  False      False  False  False
2  False      False  False  False
3  False      False  False  False
4   True       True  False  False
5   True      False  False  False

In [133]:
people_df.dtypes

email        object
full_name    object
first        object
last         object
dtype: object

In [134]:
people_df.fillna(0)

          email     full_name   first    last
0  sg@email.com   sahil Gupta   sahil   Gupta
1  ay@email.com    ajit yadav    ajit   yadav
2  ss@gmail.com   shreya soni  shreya    soni
3  sk@gmail.com  sahil watney   sahil  watney
4             0             0   juned    khan
5             0    juned khan   juned    khan

In [141]:
#working on stackoverflow data
#rplace missing values
import numpy as np
df.replace(['NA','Missing'],np.nan,inplace =True)

In [138]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
63129,I am a developer by profession,True,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, full-time",I never completed any formal education,NaN,Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",NaN,Less than 1 year,Younger than 5 years,1,Very dissatisfied,Very dissatisfied,Very confident,Yes,Yes,I am actively looking for a job,I've never had a job,Write any code,Yes,How widely used or impactful my work output wo...,I had a negative experience or interaction at ...,AED,United Arab Emirates dirham,648838511.0,Monthly,1000000.0,168.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work,It's complicated,"Other place, such as a coworking space or cafe",Far below average,No,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;Other(s):,Bash/Shell/PowerShell;TypeScript,MySQL,MySQL,Android;iOS;Windows;WordPress;Other(s):,Android;iOS;Windows;WordPress;Other(s):,Angular/Angular.js;Express;jQuery;Laravel;Othe...,Angular/Angular.js;Express;jQuery;Laravel;Othe...,Ansible;Apache Spark;Torch/PyTorch,Apache Spark;Torch/PyTorch,Android Studio;Atom;Coda;Eclipse;Emacs;IPython...,Windows,"Outside of work, for personal projects",Accepting Bitcoin or other coins and tokens as...,Useful across many domains and could change ma...,Yes,Yes,Yes,I don't use social media,Online,UserID,NaN,I have never visited Stack Overflow (before to...,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,0-10 minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...",NaN,"No, not at all",NaN,Tech articles written by other developers,NaN,NaN,NaN,NaN,NaN,Yes,Too short,Easy
50499,"I am not primarily a developer, but I write co...",True,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A health science (ex. nursing, pharmacy, radio...",Participated in a full-time developer training...,"10,000 or more employees",Data or business analyst;Database administrato...,7,27,7,Very dissatisfied,Very dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",More than 4 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Opportunities for professional development;Div...,"Something else changed (education, award, medi...",AFN,Afghan afghani,960000.0,Monthly,153216.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Time spent com...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",8.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have a great deal of influence,C#;HTML/CSS;JavaScript;SQL;VBA,C#;HTML/CSS;JavaScript;R;SQL;TypeScript;VBA,Microsoft SQL Server;PostgreSQL;SQLite,MariaDB;MongoDB;Microsoft SQL Server;PostgreSQ...,NaN,Android,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery;React.js;Vue.js,.NET,.NET;.NET Core;Node.js;Xamarin,Visual Studio,Windows,I do not use containers,Implementing our own cryptocurrency,NaN,Yes,Yes,Yes,WhatsApp,Online,Login,2013,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,NaN,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
39258,I am a developer by profession,True,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Database administrator;Designer;Developer, bac...",2,22,1,Very satisfied,Very satisfied,Very confident,No,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",AFN,Afghan afghani,120000.0,Monthly,19152.0,49.0,There is a schedule and/or spec (made by me or...,Not enough people for the workload;Time spent ...,Less than once per month / Never,Office,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have some influence,HTML/CSS;JavaScript;PHP;SQL;TypeScript,C#;Dart;JavaScript;SQL;TypeScript,MariaDB;MongoDB;MySQL;PostgreSQL,Couchbase;Firebase;MariaDB;MongoDB;Redis,Android;AWS;Linux;Windows;WordPress,Android;AWS;Docker;Heroku;iOS;Linux;Raspberry ...,Angular/Angular.js;Drupal;Express;Laravel,Angular/Angular.js;Drupal;Express,Cordova;Node.js,Hadoop;Node.js,Notepad++;PHPStorm;Vim;Visual Studio Code,Linux-based,Production,NaN,NaN,Yes,Yes,No,Facebook,Online,Login,2016,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,Yes,NaN,"Yes, somewhat",NaN,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,East Asian;South Asian,Yes,Too long,Easy
58450,I am a developer by profession,True,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",6,20,2,Neither satisfied nor dissatisfied,Slightly satisfied,Very confident,Yes,Yes,I am actively looking for a job,1-2 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,"Languages, frameworks, and other technologies ...",I had a negative experience or interaction at ...,AFN,Afghan afghani,110000.0,Monthly,17556.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment,It's complicated,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have little or no influence,Assembly;C;C++;HTML/CSS;Java;PHP;SQL,C;C++;HTML/CSS;Java;JavaScript;SQL;TypeScript,MySQL;PostgreSQL,MySQL;PostgreSQL,Linux;Windows,Windows,NaN,Spring,NaN,Node.js,IntelliJ;Notepad++,Windows,Development,Accepting Bitcoin or other coins and tokens as...,Useful for immutable record keeping outside of...,Yes,Yes,Yes,Facebook,Online,Handle,NaN,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech articles written by other developers,26.0,Man,No,Straight / Heterosexual,South Asian,No,Too long,Neither easy nor difficult
7085,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",2-9 employees,"Developer, full-stack",7,19,6,Slightly dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,AFN,Afghan afghani,90000.0,Monthly,14364.0,30.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Lack of s...,About half the time,Office,Average,"Yes, because I see value in code review",3.0,NaN,NaN,NaN,HTML/CSS;JavaScript;PHP,JavaScript;Kotlin;PHP,MySQL,MongoDB;MySQL;Redis,Linux;MacOS;Other(s):,Linux;MacOS;Other(s):,jQuery;Laravel;Vue.js,ASP.NET;jQuery;Laravel;Vue.js,NaN,React Native,Sublime Text;Visual Studio Code,MacOS,"Development;Outside of work, for personal proj...",NaN,NaN,Yes,Also Yes,Yes,Instagram,Online,UserID,2016,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Industry news about technologies you're intere...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult

In [144]:
df.set_index('Respondent',inplace=True)
df['YearsCode'].head(10)

Respondent
1       4
2     NaN
3       3
4       3
5      16
6      13
7       6
8       8
9      12
10     12
Name: YearsCode, dtype: object

In [151]:
df['YearsCode'] = df['YearsCode'].astype(float)

In [152]:
df['YearsCode'].unique()

array([ 4., nan,  3., 16., 13.,  6.,  8., 12.,  2.,  5., 17., 10., 14.,
       35.,  7.,  0., 30.,  9., 26., 40., 19., 15., 20., 28., 25.,  1.,
       22., 11., 33., 50., 41., 18., 34., 24., 23., 42., 27., 21., 36.,
       32., 39., 38., 31., 37., 51., 29., 44., 45., 48., 46., 43., 47.,
       49.])

In [149]:
df['YearsCode'].replace('Less than 1 year',0,inplace=True)
df['YearsCode'].replace('More than 50 years',51,inplace=True)

In [153]:
df['YearsCode'].mean()

11.662114216834588

In [154]:
df['YearsCode'].median()

9.0

In [155]:
df['YearsCode'].describe()

count    87938.000000
mean        11.662114
std          9.152772
min          0.000000
25%          5.000000
50%          9.000000
75%         15.000000
max         51.000000
Name: YearsCode, dtype: float64