# Part 1: introduction

In [251]:
import pandas as pd

In [252]:
df = pd.read_csv("./developer_survey_2019/survey_results_public.csv")

In [253]:
df.shape

(88883, 85)

In [254]:
#get the first five rows of the complete data
#df.head()

In [255]:
#get the general information of the data
#df.info()

In [256]:
pd.set_option("display.max_columns",85)
pd.set_option("display.max_rows",85)

In [257]:
schema_df = pd.read_csv("./developer_survey_2019/survey_results_schema.csv", index_col='Column')

In [258]:
#schema_df

#Part 2: DataFrames

In [259]:
people ={
    "name":["sahil","ajit","shreya"],
    "last":["gupta","yadav","soni"],
    "email":["sg@email.com","ay@email.com","ss@email.com"]
}

In [260]:
people['email']

['sg@email.com', 'ay@email.com', 'ss@email.com']

In [261]:
type(people['email'])

list

Dataframe can be understood by reading a python dictionay, to convert to dataframe we can use pd.DataFrame() method

In [262]:
people_df= pd.DataFrame(people)
people_df

     name   last         email
0   sahil  gupta  sg@email.com
1    ajit  yadav  ay@email.com
2  shreya   soni  ss@email.com

In [263]:
people_df['email'] # people.email will give same output

0    sg@email.com
1    ay@email.com
2    ss@email.com
Name: email, dtype: object

In [264]:
type(people_df['email'])

pandas.core.series.Series

In [265]:
people_df[['name','email']]

     name         email
0   sahil  sg@email.com
1    ajit  ay@email.com
2  shreya  ss@email.com

In [266]:
type(people_df[['name','email']])

pandas.core.frame.DataFrame

In [267]:
people_df.columns

Index(['name', 'last', 'email'], dtype='object')

In [268]:
#to get rows
people_df.iloc[[0,2]]

     name   last         email
0   sahil  gupta  sg@email.com
2  shreya   soni  ss@email.com

In [269]:
#get rows for some specific columns
people_df.iloc[[0,2],[2]]

          email
0  sg@email.com
2  ss@email.com

In [270]:
people_df.loc[[0,1],['last','name']] #can get dataframes by changing the columns order

    last   name
0  gupta  sahil
1  yadav   ajit

Working on stackoverflow data

In [271]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [272]:
#how many of answered yes and no
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [273]:
#get specific row and columns 
df.loc[[0,3,5,56],'Hobbyist']

0     Yes
3      No
5     Yes
56    Yes
Name: Hobbyist, dtype: object

In [274]:
df.loc[0:10,'Hobbyist'] #list slicing on rows

0     Yes
1      No
2     Yes
3      No
4     Yes
5     Yes
6      No
7     Yes
8     Yes
9     Yes
10    Yes
Name: Hobbyist, dtype: object

In [275]:
df.loc[0:10,'Hobbyist':'Employment'] #list slicing on rows as well as on columns ; boundaries are inclusive

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time
3,No,Never,The quality of OSS and closed source software ...,Employed full-time
4,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time
5,Yes,Never,The quality of OSS and closed source software ...,Employed full-time
6,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em..."
7,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work"
8,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time
9,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time
10,Yes,Once a month or more often,The quality of OSS and closed source software ...,NaN

# part 3: Indexing

In [276]:
#using people_df for simplicity

people_df['email']

0    sg@email.com
1    ay@email.com
2    ss@email.com
Name: email, dtype: object

In [277]:
people_df.set_index('email',inplace=True)

In [278]:
people_df

                name   last
email
sg@email.com   sahil  gupta
ay@email.com    ajit  yadav
ss@email.com  shreya   soni

In [279]:
people_df.loc['sg@email.com',['last','name']]

last    gupta
name    sahil
Name: sg@email.com, dtype: object

In [280]:
#to reset index
people_df.reset_index(inplace=True)
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [281]:
#working on stackoverflow data

df.set_index('Respondent',inplace=True)

In [282]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [283]:
#df.loc[1] #get the 1st respondent data

In [284]:
schema_df.loc['MgrIdiot','QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [285]:
schema_df.sort_index(ascending=False,inplace=True)

# Part 4: Filtering

In [286]:
#we can get the vlaues from the dataframe for a specific conditinons,
# here below we get the name of the person who's lastname is 'yadav'
filt = (people_df['last'] == 'yadav')

In [287]:
people_df[filt][['name']] #gives dataframe

   name
1  ajit

In [288]:
people_df.loc[filt,'email'] #gives series

1    ay@email.com
Name: email, dtype: object

In [289]:
filt = (people_df['name'] == 'sahil') | (people_df['last'] == 'soni')

In [290]:
people_df[filt]

          email    name   last
0  sg@email.com   sahil  gupta
2  ss@email.com  shreya   soni

In [291]:
people_df[~filt] #not filter

          email  name   last
1  ay@email.com  ajit  yadav

In [292]:
#working on stackoverflow data
high_salary = (df['ConvertedComp']>70000)
df.loc[high_salary,['Country','LanguageWorkedWith','ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
9,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
16,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88879,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88882,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [293]:
countaries = ['India','Canada']
#this filter only return values of the countries listed above. moreover we are adding one more condition that 
# get the values of those developers who have some experience in python language
filt = df['Country'].isin(countaries) & (df['LanguageWorkedWith'].str.contains('Python',na=False))

In [294]:
#filter itself returns the series of the statisfied rows form the table 
filt

Respondent
1        False
2        False
3        False
4        False
5        False
         ...
88377    False
88601    False
88802    False
88816    False
88863    False
Length: 88883, dtype: bool

In [295]:
df[filt]['Student'].value_counts() # counts values gives the frequency of the categorical columns

No                2925
Yes, full-time    1490
Yes, part-time     147
Name: Student, dtype: int64

# Part 5: updating rows and columns

In [296]:
people_df.columns = ['first_name','last_name','email']

In [297]:
people_df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [298]:
people_df.columns = [x.lower() for x in people_df.columns]

In [299]:
people_df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [300]:
people_df.rename(columns={'first_name':'email','last_name':'first','email':'last'},inplace=True)

In [301]:
people_df

          email   first   last
0  sg@email.com   sahil  gupta
1  ay@email.com    ajit  yadav
2  ss@email.com  shreya   soni

In [302]:
people_df.loc[2]= ['pb@gmail','pranay','bagrechaa']

In [303]:
people_df

          email   first       last
0  sg@email.com   sahil      gupta
1  ay@email.com    ajit      yadav
2      pb@gmail  pranay  bagrechaa

In [304]:
people_df.loc[2,['last','email']] = ['soni','ss@gmail.com']

In [305]:
#people_df.loc[2,['first']] = ['shreya'] is same as
people_df.at[2,['first']] = ['shreya']

 Be careful while modifying data, always reassign values via .loc\[\] or .at[]
 When filter is applied to the data without using 'loc' or 'at' it returns the copy of the dataframe statisfied to filter
 eg: poeple_df\[(some kind of filter)\] will gives copy, modification of the data will fail.
 the link in warning explains the diffrence.

In [306]:
filt = people_df['first'] == 'sahil'
people_df[filt]['last'] = 'Gupta'

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

To modify data successfully use .loc or .at with filter.

In [307]:
people_df.loc[filt,['last']] = 'Gupta'
people_df

          email   first   last
0  sg@email.com   sahil  Gupta
1  ay@email.com    ajit  yadav
2  ss@gmail.com  shreya   soni

### four methods for accessing and updating
### 1) apply
### 2) applymap
### 3) map
### 4) replace

---
1) apply

In [308]:
people_df['email'].apply(len)

0    12
1    12
2    12
Name: email, dtype: int64

In [309]:
def update_email(email):
    return email.upper()

people_df['email'].apply(update_email) 
#this does'nt change the original values to  do it just with the update columns

0    SG@EMAIL.COM
1    AY@EMAIL.COM
2    SS@GMAIL.COM
Name: email, dtype: object

In [310]:
people_df['email'].apply(lambda x: x.lower())

0    sg@email.com
1    ay@email.com
2    ss@gmail.com
Name: email, dtype: object

To get the length of the dataframe we can easily use apply function of len with dataframe
axis='rows' for length of rows

In [311]:
people_df.apply(len,axis='columns')

0    3
1    3
2    3
dtype: int64

In [312]:
people_df.apply(pd.Series.min)

email    ay@email.com
first            ajit
last            Gupta
dtype: object

2) applymap, only used for Dataframe for every individual values

In [313]:
people_df.applymap(len)

   email  first  last
0     12      5     5
1     12      4     5
2     12      6     4

 3) map function takes key:value pairs which replace each occurence of the key with the given value and makes every "not mentioned" keys to NaN
 
4) whereas replace method does same as map but keep values as it was originally which are not mentioned.

#### working  on stackoverflow data

In [314]:
df.rename(columns= {'ConvertedComp': 'SalaryUSD'},inplace=True)

In [315]:
#change hobbyist values to boolean
df['Hobbyist'] = df['Hobbyist'].map({'Yes':True,'No':False})
df['Hobbyist']

Respondent
1         True
2        False
3         True
4        False
5         True
         ...
88377     True
88601    False
88802    False
88816    False
88863     True
Name: Hobbyist, Length: 88883, dtype: bool

#### adding and removing columns

In [316]:
people_df['full_name'] = people_df['first']+' '+people_df['last']

In [317]:
people_df

          email   first   last    full_name
0  sg@email.com   sahil  Gupta  sahil Gupta
1  ay@email.com    ajit  yadav   ajit yadav
2  ss@gmail.com  shreya   soni  shreya soni

In [318]:
#remobe first and last name column 
people_df.drop(columns=['first','last'],inplace=True)

In [319]:
people_df

          email    full_name
0  sg@email.com  sahil Gupta
1  ay@email.com   ajit yadav
2  ss@gmail.com  shreya soni

In [320]:
# I realized i need those deleted columns
people_df['full_name'].str.split(' ',expand=True)

        0      1
0   sahil  Gupta
1    ajit  yadav
2  shreya   soni

In [321]:
people_df[['first','last']] = people_df['full_name'].str.split(' ',expand=True)

In [322]:
people_df

          email    full_name   first   last
0  sg@email.com  sahil Gupta   sahil  Gupta
1  ay@email.com   ajit yadav    ajit  yadav
2  ss@gmail.com  shreya soni  shreya   soni

In [323]:
#adding rows 
people_df.append({'first':'Juned'},ignore_index=True)

          email    full_name   first   last
0  sg@email.com  sahil Gupta   sahil  Gupta
1  ay@email.com   ajit yadav    ajit  yadav
2  ss@gmail.com  shreya soni  shreya   soni
3           NaN          NaN   Juned    NaN

In [324]:
#append new dataframe
new_people = {
    'first':['mark','lucy'],
    'last': ['watney','blake']
}
people_df2 = pd.DataFrame(new_people)

In [325]:
people_df = people_df.append(people_df2,ignore_index=True)

In [326]:
#removing rows
people_df.drop([3,4],inplace=True)

# Part 6: Sorting data

In [327]:
people_df.sort_values(by="first" , ascending=False)

          email    full_name   first   last
2  ss@gmail.com  shreya soni  shreya   soni
0  sg@email.com  sahil Gupta   sahil  Gupta
1  ay@email.com   ajit yadav    ajit  yadav

In [328]:
people_df =people_df.append({'email':'sk@gmail.com','full_name':'sahil watney','first':'sahil','last':'watney'},ignore_index=True)

In [329]:
#if last_name is same then it will sort with first name
people_df.sort_values(by=['last','first'], ascending=[False,True])

          email     full_name   first    last
1  ay@email.com    ajit yadav    ajit   yadav
3  sk@gmail.com  sahil watney   sahil  watney
2  ss@gmail.com   shreya soni  shreya    soni
0  sg@email.com   sahil Gupta   sahil   Gupta

In [331]:
people_df['email'].sort_values()

1    ay@email.com
0    sg@email.com
3    sk@gmail.com
2    ss@gmail.com
Name: email, dtype: object

#### working on stackoverlfow data

In [332]:
df.sort_values(by='Country',inplace=True)

In [336]:
df[['Country','SalaryUSD']].head(50)

                Country  SalaryUSD
Respondent
39258       Afghanistan    19152.0
63129       Afghanistan  1000000.0
85715       Afghanistan        NaN
50767       Afghanistan        NaN
2782        Afghanistan        NaN
63019       Afghanistan        NaN
6417        Afghanistan        NaN
40000       Afghanistan        NaN
88731       Afghanistan        NaN
48436       Afghanistan     4464.0
10746       Afghanistan     3996.0
62525       Afghanistan        NaN
49702       Afghanistan        NaN
33178       Afghanistan        NaN
60946       Afghanistan        NaN
86362       Afghanistan        NaN
88582       Afghanistan        NaN
28638       Afghanistan        0.0
722         Afghanistan        0.0
26340       Afghanistan        NaN
86932       Afghanistan        NaN
85825       Afghanistan        NaN
7085        Afghanistan    14364.0
7353        Afghanistan        NaN
87091       Afghanistan        NaN
58760       Afghanistan        NaN
74386       Afghanistan        NaN
29045       Afghanistan        NaN
51859       Afghanistan        NaN
45854       Afghanistan        NaN
47110       Afghanistan        NaN
44403       Afghanistan        NaN
22450       Afghanistan     7980.0
8149        Afghanistan     1596.0
80926       Afghanistan        NaN
59560       Afghanistan        NaN
60569       Afghanistan        NaN
37802       Afghanistan        NaN
29736       Afghanistan     1116.0
43106       Afghanistan        NaN
12310       Afghanistan        NaN
58450       Afghanistan    17556.0
62168       Afghanistan        NaN
50499       Afghanistan   153216.0
78817           Albania     4968.0
57419           Albania        NaN
49757           Albania        NaN
41608           Albania        NaN
33385           Albania        NaN
6716            Albania    60000.0

In [337]:
# sort on country ascending and salary in descending order
df.sort_values(by=['Country','SalaryUSD'],ascending=[True,False],inplace=True)

In [338]:
df[['Country','SalaryUSD']].head(50)

                Country  SalaryUSD
Respondent
63129       Afghanistan  1000000.0
50499       Afghanistan   153216.0
39258       Afghanistan    19152.0
58450       Afghanistan    17556.0
7085        Afghanistan    14364.0
22450       Afghanistan     7980.0
48436       Afghanistan     4464.0
10746       Afghanistan     3996.0
8149        Afghanistan     1596.0
29736       Afghanistan     1116.0
28638       Afghanistan        0.0
722         Afghanistan        0.0
85715       Afghanistan        NaN
50767       Afghanistan        NaN
2782        Afghanistan        NaN
63019       Afghanistan        NaN
6417        Afghanistan        NaN
40000       Afghanistan        NaN
88731       Afghanistan        NaN
62525       Afghanistan        NaN
49702       Afghanistan        NaN
33178       Afghanistan        NaN
60946       Afghanistan        NaN
86362       Afghanistan        NaN
88582       Afghanistan        NaN
26340       Afghanistan        NaN
86932       Afghanistan        NaN
85825       Afghanistan        NaN
7353        Afghanistan        NaN
87091       Afghanistan        NaN
58760       Afghanistan        NaN
74386       Afghanistan        NaN
29045       Afghanistan        NaN
51859       Afghanistan        NaN
45854       Afghanistan        NaN
47110       Afghanistan        NaN
44403       Afghanistan        NaN
80926       Afghanistan        NaN
59560       Afghanistan        NaN
60569       Afghanistan        NaN
37802       Afghanistan        NaN
43106       Afghanistan        NaN
12310       Afghanistan        NaN
62168       Afghanistan        NaN
38308           Albania   187668.0
3787            Albania   114550.0
9270            Albania    74474.0
6716            Albania    60000.0
10303           Albania    57300.0
66280           Albania    41244.0

In [339]:
df['SalaryUSD'].nlargest(10) #is same as df.nlargest(10,'SalaryUSD')

Respondent
25983    2000000.0
87896    2000000.0
22013    2000000.0
28243    2000000.0
72732    2000000.0
78151    2000000.0
80200    2000000.0
52132    2000000.0
75561    2000000.0
32250    2000000.0
Name: SalaryUSD, dtype: float64

In [340]:
 df.nsmallest(10,'SalaryUSD') #but this will result with complete dataframe instead of Series

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
28638,I am a developer by profession,True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,NaN,NaN,NaN,36,13,16,Very dissatisfied,Very dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NaN,NaN,NaN,NaN,NaN,AFN,Afghan afghani,3.0,Monthly,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Java;Objective-C;O...,Bash/Shell/PowerShell;C;C++;Java;Objective-C;O...,MySQL;SQLite,MySQL;SQLite,Android;iOS;Linux;MacOS,Android;iOS;Linux,jQuery,NaN,TensorFlow;Unity 3D,Hadoop;TensorFlow;Unity 3D,Emacs,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,No,NaN,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,6-10 times per week,The other resource was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","No, not at all",A lot less welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN
722,I am a developer by profession,False,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,NaN,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,Less than 1 year,Younger than 5 years,Less than 1 year,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,NaN,No,NaN,I heard about a job opportunity (from a recrui...,AFN,Afghan afghani,1.0,Yearly,0.0,1.0,NaN,NaN,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",1.0,"No, and I'm glad we don't",NaN,I have little or no influence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,SIGH,What?,NaN,Neither,NaN,2008,Multiple times per day,NaN,More than 10 times per week,The other resource was much faster,60+ minutes,Not sure / can't remember,NaN,Yes,Yes,Not sure,Not applicable - I did not use Stack Overflow ...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Too long,Difficult
13825,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,NaN,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,13,83,Less than 1 year,Very dissatisfied,Very satisfied,NaN,NaN,NaN,I am actively looking for a job,NA - I am an independent contractor or self em...,Complete a take-home project;Solve a brain-tea...,Yes,Financial performance or funding status of the...,"Something else changed (education, award, medi...",AFN,Afghan afghani,1.0,Yearly,0.0,168.0,NaN,Being tasked with non-development work;Non-wor...,About half the time,Home,Far above average,No,NaN,"Yes, it's part of our process",NaN,I have a great deal of influence,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,NaN,NaN,I do not use containers,NaN,An irresponsible use of resources,No,Yes,Yes,NaN,Neither,NaN,2015,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",A lot less welcome now than last year,NaN,56.0,NaN,NaN,NaN,NaN,Yes,Too short,Easy
40913,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Armenia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",2-9 employees,"Developer, desktop or enterprise applications;...",7,15,4,Slightly satisfied,Slightly satisfied,Very confident,Not sure,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",AMD,Armenian dram,0.0,Monthly,0.0,40.0,There's no schedule or spec; I work on what se...,"Meetings;Non-work commitments (parenting, scho...","Less than half the time, but at least one day ...",Office,A little above average,"Yes, because I see value in code review",3.0,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;C;C++;Java;JavaScript;Py...,C;C++;Java;Python;SQL;TypeScript,Elasticsearch;MariaDB;MongoDB;MySQL;Redis,MariaDB;MongoDB;MySQL,Arduino;AWS;Docker;Linux;MacOS;Raspberry Pi;Sl...,Arduino;Linux;MacOS;Raspberry Pi,ASP.NET;Django;Flask,Django;Flask,.NET;Node.js;TensorFlow;Torch/PyTorch,Node.js,IntelliJ;IPython / Jupyter;Sublime Text;Vim,Linux-based,Production,Not at all,A passing fad,No,SIGH,Yes,Facebook,In real life (in person),Username,2013,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers,22.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
30630,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,2-9 employees,"Database administrator;Developer, back-end;Dev...",35,7,30,Neither satisfied nor dissatisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,Interview with people in peer roles;Interview ...,No,Industry that I'd be working in;Office environ...,I heard about a job opportunity (from a recrui...,AUD,Australian dollar,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what se...,Distracting work environment;Non-work commitme...,It's complicated,"Other place, such as a coworking space or cafe",A little above average,"Yes, because I see value in code review",10.0,"No, but I think we should",NaN,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Ruby,Elixir;Ruby;TypeScript,PostgreSQL,PostgreSQL,AWS;iOS,Android;AWS;iOS,Ruby on Rails;Vue.js,Ruby on Rails;Vue.js,Chef;React Native,React Native,Sublime Text;TextMate;Vim;Xcode,MacOS,I do not use containers,Not at all,An irresponsible use of resources,Yes,"Fortunately, someone else has that title",No,Reddit,Online,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",A lot less welcome now than last year,NaN,43.0,NaN,No,NaN,NaN,No,Appropriate in length,Easy
69049,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,2-9 employees,"Developer, full-stack;Engineering manager",17,12,14,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",AUD,Australian dollar,0.0,Yearly,0.0,25.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Time spent com...,All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",1.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C#;Go;HTML/CSS;JavaScr...,Dart;Elixir;JavaScript;Kotlin;Python;R;Ruby;Rust,PostgreSQL;SQLite,Cassandra;PostgreSQL;Redis,Android;Arduino;Google Cloud Platform;iOS;Linu...,Google Cloud Platform;Heroku;Kubernetes;Linux;...,Ruby on Rails,Ruby on Rails;Vue.js,.NET;React Native,Ansible;Flutter;Hadoop;Pandas;React Native,IntelliJ;Visual Studio;Visual Studio Code;Xcode,MacOS,Production,NaN,A passing fad,No,Also Yes,Yes,Reddit,In real life (in person),Username,2008,A few times per week,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Not sure / can't remember,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",Just as welcome now as I felt last year,NaN,34.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
19340,"I am not primarily a developer, but I write co...",True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",NaN,Austria,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Fine arts or performing arts (ex. graphic desi...,Taken an online course in programming or softw...,NaN,NaN,10,20,5,Neither satisfied nor dissatisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",3-4 years ago,Interview with people in peer roles;Interview ...,No,Office environment or company culture;Opportun...,I was preparing for a job search,CHF,Swiss franc,0.0,Monthly,0.0,35.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,Average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have a great deal of influence,Assembly;C;Elixir;HTML/CSS;Java;JavaScript;Pyt...,Clojure,PostgreSQL;SQLite,NaN,Arduino;Raspberry Pi,Arduino;Raspberry Pi,Other(s):,Other(s):,NaN,NaN,IntelliJ;Sublime Text,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful for immutable record keeping outside of...,No,Also Yes,Yes,NaN,In real life (in person),Username,2010,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,NaN,32.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
16214,"I am not primarily a developer, but I write co...",True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",NaN,20 to 99 employees,"Engineer, data;Engineering manager;Product man...",20,16,20,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Interview with people in peer roles,No,Financial performance or funding status of the...,I was preparing for a job search,EUR,European Euro,0.0,Yearly,0.0,10.0,There's no schedule or spec; I work on what se...,Lack of support from management;Meetings;Time ...,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,No,NaN,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,Java;PHP;Other(s):,Java;PHP;Other(s):,MariaDB;MySQL,MariaDB;MySQL,Android;Linux;Raspberry Pi;Windows;WordPress,Android;Linux;Raspberry Pi;Windows;WordPress,jQuery;Spring,jQuery;Spring,NaN,NaN,Android Studio;Eclipse;IntelliJ;NetBeans,Linux-based,I do not use containers,Not at all,NaN,No,Yes,What?,WhatsApp,Neither,NaN,2008,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,99.0,NaN,No,NaN,NaN,NaN,Too long,Easy
29355,I am a developer by profession,True,Never,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",Bosnia and Herzegovina,"Yes, part-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","Just me - I am a freelancer, sole proprietor, ...",NaN,10,10,6,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,Less than a year ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Specific depar...,"Something else changed (education, award, medi...",BAM,Bosnia and Herzegovina convertible mark,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Inadequ...,It's complicated,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",20.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Python;Ruby;Other(s):,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;Oth...,NaN,NaN,Linux;MacOS;Microsoft Azure;Raspberry Pi;Windows,Android;Arduino;AWS;iOS;Linux;MacOS;Raspberry ...,NaN,NaN,Pandas;TensorFlow;Torch/PyTorch;Unity 3D;Unrea...,.NET;Torch/PyTorch;Unity 3D,Android Studio;Emacs;PyCharm;Visual Studio;Vis...,Linux-based,I do not use containers,NaN,A passing fad,Yes,Also Yes,Yes,YouTube,In real life (in person),Username,2013,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,NaN,No,NaN,NaN,NaN,Too long,Easy
1685,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Brazil,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...","Designer;Developer, full-stack;Developer, game...",8,16,3,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,Specific department or team I'd be working on;...,I was preparing for a job search,BRL,Brazilian real,0.0,Monthly,0.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Toxic wo...,All or almost all the time (I'm full-time remote),Home,Average,"Yes, because I see value in code review",6.0,NaN,NaN,NaN,Elixir;HTML/CSS;JavaScript;PHP;Python,C#;Kotlin;Python,Cassandra;MariaDB;MongoDB;PostgreSQL,Cassandra;MariaDB;MongoDB;PostgreSQL,Docker;Kubernetes;MacOS,Android;Linux;Windows,Laravel,Django;Flask;Laravel;Vue.js,Node.js,.NET;Node.js;Unity 3D;Other(s):,Android Studio;PHPStorm;PyCharm;Visual Studio ...,Windows,Development,NaN,Useful across many domains and could change ma...,No,Yes,Yes,WhatsApp,In real life (in person),NaN,2010,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Neither easy nor difficult