# Part 1: introduction

In [148]:
import pandas as pd

In [149]:
df = pd.read_csv("./developer_survey_2019/survey_results_public.csv")

In [150]:
df.shape

(88883, 85)

In [151]:
#get the first five rows of the complete data
#df.head()

In [152]:
#get the general information of the data
#df.info()

In [153]:
pd.set_option("display.max_columns",85)
pd.set_option("display.max_rows",85)

In [154]:
schema_df = pd.read_csv("./developer_survey_2019/survey_results_schema.csv", index_col='Column')

In [155]:
#schema_df

#Part 2: DataFrames

In [156]:
people ={
    "name":["sahil","ajit","shreya"],
    "last":["gupta","yadav","soni"],
    "email":["sg@email.com","ay@email.com","ss@email.com"]
}

In [157]:
people['email']

['sg@email.com', 'ay@email.com', 'ss@email.com']

In [158]:
type(people['email'])

list

Dataframe can be understood by reading a python dictionay, to convert to dataframe we can use pd.DataFrame() method

In [159]:
people_df= pd.DataFrame(people)
people_df

     name   last         email
0   sahil  gupta  sg@email.com
1    ajit  yadav  ay@email.com
2  shreya   soni  ss@email.com

In [160]:
people_df['email'] # people.email will give same output

0    sg@email.com
1    ay@email.com
2    ss@email.com
Name: email, dtype: object

In [161]:
type(people_df['email'])

pandas.core.series.Series

In [162]:
people_df[['name','email']]

     name         email
0   sahil  sg@email.com
1    ajit  ay@email.com
2  shreya  ss@email.com

In [163]:
type(people_df[['name','email']])

pandas.core.frame.DataFrame

In [164]:
people_df.columns

Index(['name', 'last', 'email'], dtype='object')

In [165]:
#to get rows
people_df.iloc[[0,2]]

     name   last         email
0   sahil  gupta  sg@email.com
2  shreya   soni  ss@email.com

In [166]:
#get rows for some specific columns
people_df.iloc[[0,2],[2]]

          email
0  sg@email.com
2  ss@email.com

In [167]:
people_df.loc[[0,1],['last','name']] #can get dataframes by changing the columns order

    last   name
0  gupta  sahil
1  yadav   ajit

Working on stackoverflow data

In [168]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [169]:
#how many of answered yes and no
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [170]:
#get specific row and columns 
df.loc[[0,3,5,56],'Hobbyist']

0     Yes
3      No
5     Yes
56    Yes
Name: Hobbyist, dtype: object

In [171]:
df.loc[0:10,'Hobbyist'] #list slicing on rows

0     Yes
1      No
2     Yes
3      No
4     Yes
5     Yes
6      No
7     Yes
8     Yes
9     Yes
10    Yes
Name: Hobbyist, dtype: object

In [172]:
df.loc[0:10,'Hobbyist':'Employment'] #list slicing on rows as well as on columns ; boundaries are inclusive

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time
3,No,Never,The quality of OSS and closed source software ...,Employed full-time
4,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time
5,Yes,Never,The quality of OSS and closed source software ...,Employed full-time
6,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em..."
7,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work"
8,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time
9,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time
10,Yes,Once a month or more often,The quality of OSS and closed source software ...,NaN

# part 3: Indexing

In [173]:
#using people_df for simplicity

people_df['email']

0    sg@email.com
1    ay@email.com
2    ss@email.com
Name: email, dtype: object

In [174]:
people_df.set_index('email',inplace=True)

In [175]:
people_df

                name   last
email
sg@email.com   sahil  gupta
ay@email.com    ajit  yadav
ss@email.com  shreya   soni

In [176]:
people_df.loc['sg@email.com',['last','name']]

last    gupta
name    sahil
Name: sg@email.com, dtype: object

In [177]:
#to reset index
people_df.reset_index(inplace=True)
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [178]:
#working on stackoverflow data

df.set_index('Respondent',inplace=True)

In [179]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [180]:
#df.loc[1] #get the 1st respondent data

In [181]:
schema_df.loc['MgrIdiot','QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [182]:
schema_df.sort_index(ascending=False,inplace=True)

# Part 4: Filtering

In [183]:
#we can get the vlaues from the dataframe for a specific conditinons,
# here below we get the name of the person who's lastname is 'yadav'
filt = (people_df['last'] == 'yadav')

In [184]:
people_df[filt][['name']] #gives dataframe

   name
1  ajit

In [185]:
people_df.loc[filt,'email'] #gives series

1    ay@email.com
Name: email, dtype: object

In [186]:
filt = (people_df['name'] == 'sahil') | (people_df['last'] == 'soni')

In [187]:
people_df[filt]

          email    name   last
0  sg@email.com   sahil  gupta
2  ss@email.com  shreya   soni

In [188]:
people_df[~filt] #not filter

          email  name   last
1  ay@email.com  ajit  yadav

In [189]:
#working on stackoverflow data
high_salary = (df['ConvertedComp']>70000)
df.loc[high_salary,['Country','LanguageWorkedWith','ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
9,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
16,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88879,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88882,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [190]:
countaries = ['India','Canada']
#this filter only return values of the countries listed above. moreover we are adding one more condition that 
# get the values of those developers who have some experience in python language
filt = df['Country'].isin(countaries) & (df['LanguageWorkedWith'].str.contains('Python',na=False))

In [191]:
#filter itself returns the series of the statisfied rows form the table 
filt

Respondent
1        False
2        False
3        False
4        False
5        False
         ...
88377    False
88601    False
88802    False
88816    False
88863    False
Length: 88883, dtype: bool

In [192]:
df[filt]['Student'].value_counts() # counts values gives the frequency of the categorical columns

No                2925
Yes, full-time    1490
Yes, part-time     147
Name: Student, dtype: int64

# Part 5: updating rows and columns

In [193]:
people_df.columns = ['first_name','last_name','email']

In [194]:
people_df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [195]:
people_df.columns = [x.lower() for x in people_df.columns]

In [204]:
people_df.columns

Index(['first_name', 'last_name', 'first'], dtype='object')

In [207]:
people_df.rename(columns={'first_name':'email','last_name':'first','email':'last'},inplace=True)

In [208]:
people_df

          email   first       last
0  sg@email.com   sahil      gupta
1  ay@email.com    ajit      yadav
2      pb@gmail  pranay  bagrechaa

In [209]:
people_df.loc[2]= ['pb@gmail','pranay','bagrechaa']

In [210]:
people_df

          email   first       last
0  sg@email.com   sahil      gupta
1  ay@email.com    ajit      yadav
2      pb@gmail  pranay  bagrechaa

In [211]:
people_df.loc[2,['last','email']] = ['soni','ss@gmail.com']

In [212]:
#people_df.loc[2,['first']] = ['shreya'] is same as
people_df.at[2,['first']] = ['shreya']

 Be careful while modifying data, always reassign values via .loc\[\] or .at[]
 When filter is applied to the data without using 'loc' or 'at' it returns the copy of the dataframe statisfied to filter
 eg: poeple_df\[(some kind of filter)\] will gives copy, modification of the data will fail.
 the link in warning explains the diffrence.

In [213]:
filt = people_df['first'] == 'sahil'
people_df[filt]['last'] = 'Gupta'

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

To modify data successfully use .loc or .at with filter.

In [214]:
people_df.loc[filt,['last']] = 'Gupta'
people_df

          email   first   last
0  sg@email.com   sahil  Gupta
1  ay@email.com    ajit  yadav
2  ss@gmail.com  shreya   soni

### four methods for accessing and updating
### 1) apply
### 2) applymap
### 3) map
### 4) replace

---
1) apply

In [ ]:
people_df['email'].apply(len)

In [ ]:
def update_email(email):
    return email.upper()

people_df['email'].apply(update_email) 
#this does'nt change the original values to  do it just with the update columns

In [ ]:
people_df['email'].apply(lambda x: x.lower())

To get the length of the dataframe we can easily use apply function of len with dataframe
axis='rows' for length of rows

In [ ]:
people_df.apply(len,axis='columns')

In [ ]:
people_df.apply(pd.Series.min)

2) applymap, only used for Dataframe for every individual values

In [ ]:
people_df.applymap(len)

 3) map function takes key:value pairs which replace each occurence of the key with the given value and makes every "not mentioned" keys to NaN
 
4) whereas replace method does same as map but keep values as it was originally which are not mentioned.

#### working  on stackoverflow data

In [ ]:
df.rename(columns= {'ConvertedComp': 'SalaryUSD'},inplace=True)

In [ ]:
#change hobbyist values to boolean
df['Hobbyist'] = df['Hobbyist'].map({'Yes':True,'No':False})
df['Hobbyist']

#### adding and removing columns

In [215]:
people_df['full_name'] = people_df['first']+' '+people_df['last']

In [216]:
people_df

          email   first   last    full_name
0  sg@email.com   sahil  Gupta  sahil Gupta
1  ay@email.com    ajit  yadav   ajit yadav
2  ss@gmail.com  shreya   soni  shreya soni

In [218]:
#remobe first and last name column 
people_df.drop(columns=['first','last'],inplace=True)

In [219]:
people_df

          email    full_name
0  sg@email.com  sahil Gupta
1  ay@email.com   ajit yadav
2  ss@gmail.com  shreya soni

In [222]:
# I realized i need those deleted columns
people_df['full_name'].str.split(' ',expand=True)

        0      1
0   sahil  Gupta
1    ajit  yadav
2  shreya   soni

In [231]:
people_df[['first','last']] = people_df['full_name'].str.split(' ',expand=True)

In [224]:
people_df

          email    full_name   first   last
0  sg@email.com  sahil Gupta   sahil  Gupta
1  ay@email.com   ajit yadav    ajit  yadav
2  ss@gmail.com  shreya soni  shreya   soni

In [225]:
#adding rows 
people_df.append({'first':'Juned'},ignore_index=True)

          email    full_name   first   last
0  sg@email.com  sahil Gupta   sahil  Gupta
1  ay@email.com   ajit yadav    ajit  yadav
2  ss@gmail.com  shreya soni  shreya   soni
3           NaN          NaN   Juned    NaN

In [233]:
#append new dataframe
new_people = {
    'first':['mark','lucy'],
    'last': ['watney','blake']
}
people_df2 = pd.DataFrame(new_people)

In [234]:
people_df = people_df.append(people_df2,ignore_index=True)

In [239]:
#removing rows
people_df.drop([3,4],inplace=True)